/** @typedef {object} photo
 * @property {string} id
 * @property {string} type
 * @property {string} archive
 * @property {string} userId
 * @property {string} headline
 * @property {string} description
 * @property {string} altTextAccessibility
 * @property {string[]} keywords
 * @property {string} category
 * @property {} personsShown
 * @property {number} imageRating
 * @property {string} dateCreated
 * @property {string} dateArchived
 * @property {string} creator
 * @property {string} country
 * @property {string} city
 * @property {string} creditLine
 * @property {boolean} restrictions
 * @property {string} instructions
 * @property {string} usageTerms
 * @property {string} source
 * @property {string} suppliers
 * @property {string} imageSupplierImageId
 * @property {string} jobId
 * @property {object} file
 * @property {number} file.size
 * @property {string} file.mimeType
 * @property {number} file.height
 * @property {number} file.width
 * @property {string} file.originalFilename
 * @property {object} previews
 * @property {object} previews.256
 * @property {string} previews.256.url
 * @property {number} previews.256.height
 * @property {number} previews.256.width
 * @property {object} previews.512
 * @property {string} previews.512.url
 * @property {number} previews.512.height
 * @property {number} previews.512.width
 * @property {object} previews.1024
 * @property {string} previews.1024.url
 * @property {number} previews.1024.height
 * @property {number} previews.1024.width
 * @property {object} permissions
 * @property {boolean} permissions.edit
 * @property {boolean} permissions.delete
 * @property {boolean} permissions.download
 * @property {object} _links
 * @property {string} _links.previewPage
 * @property {object} _internal
 * @property {object} _internal.origin
 * @property {string} _internal.origin.key
 * @property {string} _internal.origin.name
 * @property {string} _internal.itemId
 */
exports.unused = {}
